name: Snocko CI

on: [push]

jobs:
  build-and-push:
    name: 'Build and push image'
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/master'
    steps:
      - name: Check out the repo
        uses: actions/checkout@v2
        with:
          ref: master

      - name: 'Configure AWS credentials'
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-region:  us-east-1
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          registry-type: 'public'
      
      - name: Build, tag, and push image to Amazon ECR
        run: |
          docker build . --target=prod --tag=public.ecr.aws/s7j8l1f2/snocko:$GITHUB_SHA
          docker push public.ecr.aws/s7j8l1f2/snocko:$GITHUB_SHA