version: '3.4'

services:
  snocko:
    build:
      context: ./
      target: local
    container_name: snocko
    restart: always
    ports:
      - 8081:8081
    volumes:
      - ./:/var/www/project